[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "yfinance-cache"
version = "0.7.14"
requires-python = ">=3.9"
dependencies = [
    "yfinance>=1.0",
    "exchange_calendars>=4.10",
    "numpy>=1.26",
    "pandas>=1.5,<3",
    "scipy>=1.6.3",
    "platformdirs",
    "pulp",
]

[tool.setuptools.package-data]
yfinance_cache = ["VERSION"]
